"""
Name mappings for splitted monsters.
"""

mappings = {
    "Aboleth (and Skum) Aboleth": "Aboleth",
    "Aboleth (and Skum) Skum": "Skum",
    "Ankheg Adult": "Ankheg, Adult",
    "Ankheg Juvenile": "Ankheg, Juvenile",
    "Ape, Orangutan Female": "Ape, Orangutan Female",
    "Ape, Orangutan Male": "Ape, Orangutan Male",
    "Badger (and Badger, Giant) Badger": "Badger",
    "Badger (and Badger, Giant) Giant Badger": "Badger, Giant",
    "Bear, Quill Common": "Bear, Quill Common",
    "Bear, Quill Huge": "Bear, Quill Huge",
    "Blade Spirit Common": "Blade Spirit, Common",
    "Blade Spirit Greater": "Blade Spirit, Greater",
    "Bone Horror Common": "Bone Horror, Common",
    "Bone Horror Greater": "Bone Horror, Greater",
    "Cockroach, Giant (and Balroach) Giant": "Cockroach, Giant",
    "Cockroach, Giant (and Balroach) Balroach": "Balroach",
    "Corpse Abomination 14": "Corpse Abomination, 14",
    "Corpse Abomination 17": "Corpse Abomination, 17",
    "Corpse Abomination 20": "Corpse Abomination, 20",
    "Cu-Sidhe Common": "Cu-Sidhe, Common",
    "Cu-Sidhe Special": "Cu-Sidhe, Special",
    "Dragophant (and Dracophant, Bull) Dragophant": "Dragophant",
    "Dragophant (and Dracophant, Bull) Bull Dragophant": "Dracophant, Bull",
    "Eel, Common, Electric, Weed, & Giant Common": "Eel, Common",
    "Eel, Common, Electric, Weed, & Giant Electric": "Eel, Electric",
    "Eel, Common, Electric, Weed, & Giant Weed": "Eel, Weed",
    "Eel, Common, Electric, Weed, & Giant Giant": "Eel, Giant",
    "Elemental, Blood Staff": "Elemental, Blood Staff",
    "Elemental, Blood Device": "Elemental, Blood Device",
    "Elemental, Blood Spell": "Elemental, Blood Spell",
    "Elemental, Cold Staff": "Elemental, Cold Staff",
    "Elemental, Cold Device": "Elemental, Cold Device",
    "Elemental, Cold Spell": "Elemental, Cold Spell",
    "Elemental, Lightning Staff": "Elemental, Lightning Staff",
    "Elemental, Lightning Device": "Elemental, Lightning Device",
    "Elemental, Lightning Spell": "Elemental, Lightning Spell",
    "Elemental, Metal Staff": "Elemental, Metal Staff",
    "Elemental, Metal Device": "Elemental, Metal Device",
    "Elemental, Metal Spell": "Elemental, Metal Spell",
    "Elemental, Wood Staff": "Elemental, Wood Staff",
    "Elemental, Wood Device": "Elemental, Wood Device",
    "Elemental, Wood Spell": "Elemental, Wood Spell",
    "Fish, Crusher Fry": "Fish, Crusher Fry",
    "Fish, Crusher Juvenile": "Fish, Crusher Juvenile",
    "Fish, Crusher Adult": "Fish, Crusher Adult",
    "Fungi, Violet Small": "Fungi, Violet Small",
    "Fungi, Violet Medium": "Fungi, Violet Medium",
    "Fungi, Violet Large": "Fungi, Violet Large",
    "Fungi, Violet Huge": "Fungi, Violet Huge",
    "Ghostcap Bloom Main Bush": "Ghostcap Bloom, Main Bush",
    "Ghostcap Bloom Small Bush": "Ghostcap Bloom, Small Bush",
    "Ghoul, Sea (and Ghast, Sea) Sea-Ghoul": "Ghoul, Sea",
    "Ghoul, Sea (and Ghast, Sea) Sea-Ghast": "Ghast, Sea",
    "Grave Sentinel (Watcher, and Guardian) Grave Sentinel": "Grave Sentinel",
    "Grave Sentinel (Watcher, and Guardian) Grave Watcher": "Grave Watcher",
    "Grave Sentinel (Watcher, and Guardian) Grave Guardian": "Grave Guardian",
    "Kappa (and Suiko) Kappa": "Kappa",
    "Kappa (and Suiko) Suiko": "Suiko",
    "Lamprey Normal": "Lamprey, Normal",
    "Lamprey Giant": "Lamprey, Giant",
    "Mink (and Giant Mink) Mink": "Mink",
    "Mink (and Giant Mink) Giant Mink": "Mink, Giant",
    "Mold, Deadly Brown": "Mold, Deadly Brown",
    "Mold, Deadly Yellow": "Mold, Deadly Yellow",
    "Oculus Rex Common": "Oculus Rex Common",
    "Oculus Rex Emperor": "Oculus Rex Emperor",
    "Otter (Common and Giant) Common": "Otter, Common",
    "Otter (Common and Giant) Giant": "Otter, Giant",
    "Ray Manta": "Ray Manta",
    "Ray Pungi": "Ray Pungi",
    "Ray Sting": "Ray Sting",
    "Scarecrow, Living Normal": "Scarecrow, Living Normal",
    "Scarecrow, Living Small": "Scarecrow, Living Small",
    "Serpent Men (and Serpent Men Greater) Common": "Serpent Men, Common",
    "Serpent Men (and Serpent Men Greater) Greater": "Serpent Men, Greater",
    "Shambler (and Shambler, Lesser) Greater": "Shambler, Greater",
    "Shambler (and Shambler, Lesser) Lesser": "Shambler, Lesser",
    "Syring (and Syring Juggernaut) Syring": "Syring",
    "Syring (and Syring Juggernaut) Syring Juggernaut": "Syring Juggernaut",
    "Wolf (Winter & Worg) Winter": "Wolf, Winter",
    "Wolf (Winter & Worg) Worg": "Wolf, Worg",
    "Wolverine Normal": "Wolverine, Normal",
    "Wolverine Giant": "Wolverine, Giant",
    "Ant, Giant (and Huge, Large) Giant": "Ant, Giant",
    "Ant, Giant (and Huge, Large) Huge": "Ant, Huge",
    "Ant, Giant (and Huge, Large) Large": "Ant, Large",
    "Basilisk Common": "Basilisk, Common",
    "Basilisk Greater": "Basilisk, Greater",
    "Bat (and Bat, Giant) Bat": "Bat",
    "Bat (and Bat, Giant) Giant Bat": "Bat, Giant",
    "Cattle (including Aurochs and Bison) Cattle": "Cattle",
    "Cattle (including Aurochs and Bison) Aurochs": "Aurochs",
    "Cattle (including Aurochs and Bison) Bison": "Bison",
    "Crocodile Normal": "Crocodile, Normal",
    "Crocodile Large": "Crocodile, Large",
    "Crocodile Giant": "Crocodile, Giant",
    "Deceiver (Panther-Hydra) Common": "Deceiver (Panther-Hydra), Common",
    "Deceiver (Panther-Hydra) Greater": "Deceiver (Panther-Hydra), Greater",
    "Dinosaur, Pterodactyl (and Pteranodon) Pterodactyl": "Dinosaur, Pterodactyl",
    "Dinosaur, Pterodactyl (and Pteranodon) Pteranodon": "Dinosaur, Pteranodon",
    "Dog Normal": "Dog, Normal",
    "Dog Riding": "Dog, Riding",
    "Elemental, Air Staff": "Elemental, Air Staff",
    "Elemental, Air Device": "Elemental, Air Device",
    "Elemental, Air Spell": "Elemental, Air Spell",
    "Elemental, Earth Staff": "Elemental, Earth Staff",
    "Elemental, Earth Device": "Elemental, Earth Device",
    "Elemental, Earth Spell": "Elemental, Earth Spell",
    "Elemental, Fire Staff": "Elemental, Fire Staff",
    "Elemental, Fire Device": "Elemental, Fire Device",
    "Elemental, Fire Spell": "Elemental, Fire Spell",
    "Elemental, Water Staff": "Elemental, Water Staff",
    "Elemental, Water Device": "Elemental, Water Device",
    "Elemental, Water Spell": "Elemental, Water Spell",
    "Elephant Asiatic": "Elephant, Asiatic",
    "Elephant African": "Elephant, African",
    "Fish, Giant Barracuda Huge": "Fish, Giant Barracuda Huge",
    "Fish, Giant Barracuda Giant": "Fish, Giant Barracuda Giant",
    "Ghoul (and Ghast) Ghoul": "Ghoul",
    "Ghoul (and Ghast) Ghast": "Ghast",
    "Hawk Normal": "Hawk, Normal",
    "Hawk Giant": "Hawk, Giant",
    "Hyena (and Hyenodon) Hyena": "Hyena",
    "Hyena (and Hyenodon) Hyenodon": "Hyenodon",
    "Lizard, Monitor Large": "Lizard, Monitor Large",
    "Lizard, Monitor Huge": "Lizard, Monitor Huge",
    "Lizard, Monitor Giant": "Lizard, Monitor Giant",
    "Lizard Man Common": "Lizard Man, Common",
    "Lizard Man Subterranean": "Lizard Man, Subterranean",
    "Mammoth (and Mastodon) Mammoth": "Mammoth",
    "Mammoth (and Mastodon) Mastodon": "Mastodon",
    "Ostrich (and Emu) Ostrich": "Ostrich",
    "Ostrich (and Emu) Emu": "Emu",
    "Purple Worm 16": "Purple Worm, 16",
    "Purple Worm 17": "Purple Worm, 17",
    "Rat (and Rat, Giant) Normal": "Rat",
    "Rat (and Rat, Giant) Giant": "Rat, Giant",
    "Rhinoceros Black": "Rhinoceros, Black",
    "Rhinoceros Woolly": "Rhinoceros, Woolly",
    "Roc Normal": "Roc, Normal",
    "Roc Large": "Roc, Large",
    "Roc Giant": "Roc, Giant",
    "Shrew, Giant Common": "Shrew, Giant Common",
    "Shrew, Giant Venomous": "Shrew, Giant Venomous",
    "Snake, Pit Viper (and Rattlesnake) Normal": "Snake, Pit Viper Normal",
    "Snake, Pit Viper (and Rattlesnake) Giant": "Snake, Pit Viper Giant",
    "Squid, Giant Male": "Squid, Giant Male",
    "Squid, Giant Female": "Squid, Giant Female",
    "Troll (and Trollwife) Troll": "Troll",
    "Troll (and Trollwife) Trollwife": "Trollwife",
    "Trollkin Infant": "Trollkin, Infant",
    "Trollkin Juvenile": "Trollkin, Juvenile",
    "Trollkin Adolescent": "Trollkin, Adolescent",
    "Turtle or Tortoise Box Turtle": "Turtle",
    "Turtle or Tortoise Snapping Turtle": "Turtle, Snapping",
    "Unicorn (and Alicorn) Unicorn": "Unicorn",
    "Unicorn (and Alicorn) Alicorn": "Alicorn",
    "Weasel, Normal and Giant (or Ferret) Normal": "Weasel, Normal",
    "Weasel, Normal and Giant (or Ferret) Giant": "Weasel, Giant",
    "Wolf (and Wolf, Dire) Normal": "Wolf, Normal",
    "Wolf (and Wolf, Dire) Dire": "Wolf, Dire",
    "Zombraire (and Skeletaire) Zombraire": "Zombraire",
    "Zombraire (and Skeletaire) Skeletaire": "Skeletaire",
}
